### ISSUE TITLE
No matching version found for @snyk/cli-interface@2.2.0

### ISSUE THREAD

**Issue by igogra** [snyk/snyk-cli-interface#23]
- `node -v`: v10.16.3
- `npm -v`: 6.12.0
- `snyk -v`: 
- Command run:
npm i

### Expected behaviour
Install all dependencies in the package.json of the project

### Actual behaviour
I get the error "No matching version found for @snyk/cli-interface@2.2.0"

The installation was sucessfull until you published the last version "2.2.0" few hours ago

### Steps to reproduce
npm i

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

**Comment by lili2311** [comment]
Could you please confirm this is not a problem with the latest version?

**Comment by thisislawatts** [comment]
🧹 Closing as stale. Please reopen if required.
